name: Nightly Release

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间午夜运行
  workflow_dispatch:      # 允许手动触发
permissions:
  contents: write 
jobs:
  create-release:
    name: Upload Nightly Build
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Clone YimMenuV2
      run: |
        git clone --recursive https://github.com/YimMenu/YimMenuV2.git
        cd YimMenuV2

    - name: Translate YimMenuV2
      run: |
        cd YimMenuV2
        cp ../*.py .
        cp ../*.TTF .
        cp ../*.diff .
        cp ../*.json .
        git apply stage.diff
        python font.py
        mv MainFont.cpp src/game/frontend/fonts -Force
        python translate.py
    
    - name: Setup MSVC environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64

    - name: Generate CMake project
      run: |
        cd YimMenuV2
        cmake -D CMAKE_BUILD_TYPE=Release -S. -Bbuild -G Ninja
        
    - name: Build 64bit release DLL
      run: |
        cd YimMenuV2
        cmake --build ./build --config Release --target YimMenuV2 --

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: nightly-latest
        overwrite: true
        name: Nightly Build
        body: |
          Automatic nightly build of YimMenu
          Commit: ${{ github.sha }}
        draft: false
        prerelease: true
        files: |
          YimMenuV2/build/YimMenuV2.dll